server:
  port: 10086 #服务端口
spring:
  application:
    name: spring-cloud-eureka  #指定服务名
eureka:
  client:
    registerWithEureka: false  #服务发现，是否从Eureka中获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/ #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机10083端口）
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
